databases:
  - name: supplierhub-db
    plan: free
    databaseName: supplierhub
    user: supplierhub

services:
  - type: web
    name: supplierhub-web
    runtime: docker
    plan: free
    healthCheckPath: /up
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: ATTR_ENCRYPTED_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: supplierhub-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: supplierhub-redis
          type: redis
          property: connectionString

  - type: worker
    name: supplierhub-sidekiq
    runtime: docker
    plan: free
    dockerCommand: bundle exec sidekiq
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        fromService:
          name: supplierhub-web
          type: web
          envVarKey: SECRET_KEY_BASE
      - key: ATTR_ENCRYPTED_KEY
        fromService:
          name: supplierhub-web
          type: web
          envVarKey: ATTR_ENCRYPTED_KEY
      - key: DATABASE_URL
        fromDatabase:
          name: supplierhub-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: supplierhub-redis
          type: redis
          property: connectionString

  - type: redis
    name: supplierhub-redis
    plan: free
    maxmemoryPolicy: noeviction
