development:
  adapter: solid_cable
  silence_polling: true
  polling_interval: 0.1

test:
  adapter: test

production:
  adapter: solid_cable
  silence_polling: true
  polling_interval: 0.1
  channel_prefix: restaurant_supplier_aggregator_production
