default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: restaurant_supplier_aggregator_development

test:
  <<: *default
  database: restaurant_supplier_aggregator_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: <%= ENV.fetch("POSTGRES_DB", "supplier_hub_production") %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
