default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: restaurant_supplier_aggregator_development
  prepared_statements: false

test:
  <<: *default
  database: restaurant_supplier_aggregator_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
