default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: [critical]
      threads: 2
      processes: 1
      polling_interval: 0.1
    - queues: [default]
      threads: 2
      processes: 1
      polling_interval: 0.1
    - queues: [scraping]
      threads: 2
      processes: 1
      polling_interval: 1
    - queues: [low]
      threads: 1
      processes: 1
      polling_interval: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
