default: &default
  dispatchers:
    - polling_interval: 5
      batch_size: 100
  workers:
    - queues: [critical]
      threads: 1
      processes: 1
      polling_interval: 1
    - queues: [default]
      threads: 1
      processes: 1
      polling_interval: 2
    - queues: [scraping]
      threads: 1
      processes: 1
      polling_interval: 5
    - queues: [low]
      threads: 1
      processes: 1
      polling_interval: 10

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
